openapi: 3.0.0
info:
  title: Payment Service API
  version: 1.0.0
  description: API for Payment Operations
servers:
  - url: http://localhost:8080/
    description: Local server

paths:
  /:
    get:
      summary: Get all payments
      description: Retrieve a list of all payments.
      parameters:
        - name: number
          in: query
          required: false
          schema:
            type: string
          description: Number parameter
        - name: sename
          in: query
          required: false
          schema:
            type: string
          description: SE name parameter
      responses:
        '200':
          description: Successful response
          content:
            text/html:
              schema:
                type: string

  /mvc/payment:
    post:
      summary: Submit a payment
      description: Save a new payment.
      parameters:
        - name: number
          in: query
          required: false
          schema:
            type: string
        - name: sename
          in: query
          required: false
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PaymentDto'
      responses:
        '200':
          description: Successful response
          content:
            text/html:
              schema:
                type: string

  /mvc/createPayment:
    get:
      summary: Payment form
      description: Form for creating a payment.
      parameters:
        - name: number
          in: query
          required: false
          schema:
            type: string
        - name: sename
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            text/html:
              schema:
                type: string

components:
  schemas:
    PaymentDto:
      type: object
      properties:
        userId:
          type: string
        accountFrom:
          type: string
        accountTo:
          type: string
        amount:
          type: integer
          format: int64

